Feature/admins book crat layout
peaksoft-school/ebook-web pull request #46
Opened 2022-02-21 11:39 UTC by KenzheSan

2022-02-21 14:37 UTC, zhumabek requested changes

2022-02-21 14:37 UTC, zhumabek commented on src/components/BookCardRenderingDropdowns/BookStatusDropdown/BookStatusDropdown.js
> +<<<<<<< HEAD
шо это?

2022-02-21 14:37 UTC, zhumabek commented on src/components/BookCardRenderingDropdowns/BookStatusDropdown/BookStatusDropdown.js
> +=======
+

2022-02-21 14:37 UTC, zhumabek commented on src/components/BookCardRenderingDropdowns/BookStatusDropdown/BookStatusDropdown.js
> +>>>>>>> 00e1760282605c68c399d1f95006cfc25549a178
+

2022-02-21 14:37 UTC, zhumabek commented on src/components/UI/VendorBookCard/VendorBookCard.js
> +                  src={`http://3.123.114.41/static/download/${book.image.id}`}
вынести в константу или же еще лучше если добавить в helpers функцию  getImageUrl(id)
и кажды кто нуждается в нем будет юзать эту функцию

2022-02-21 14:37 UTC, zhumabek commented on src/components/UI/dropZone/DropZone.js
> +export default function DropZone({ avatar, setAvatar }) {
у вас тут компонент как только мы картинку выбираем он автоматически сохраняет на сервер
это плохо потому что если человек несколько раз заменит картинку все предыдущие файлы уже не нужны но они уже сохранились в базе и будут висеть там просто так как мусор
а нам ведь нужен только самый последний файл

по этому запрос на сохранение отправляем только тогда когда нажимаем  кнопку Сохранить

2022-02-21 14:37 UTC, zhumabek commented on src/components/UI/dropZone/DropZone.js
> +export default function DropZone({ avatar, setAvatar }) {
плюс еще запрос на сохранение должно осуществляться вне компонента
сейчас ваш компонент очень умный а надо сделать тупым

2022-02-21 14:37 UTC, zhumabek commented on src/config/icon.js
> +<<<<<<< HEAD
шо

2022-02-21 14:37 UTC, zhumabek commented on src/config/icon.js
> +=======
шо

2022-02-21 14:37 UTC, zhumabek commented on src/containers/admin/adminAddBook/addAudioBook/AddAudioBook.js
> +               {/* <Input
удалить если не нужен

2022-02-21 14:37 UTC, zhumabek commented on src/store/cratReducer/bookCratSlice.js
> +         const response = await fetch(
нужно юзать общий sendRequest функцию

2022-02-21 14:37 UTC, zhumabek commented on src/hooks/useHttp.js
> +const useHttp = (config) => {
разве нам нужен useHttp? может нужно удалить

2022-02-21 19:55 UTC, KenzheSan commented on src/components/BookCardRenderingDropdowns/BookStatusDropdown/BookStatusDropdown.js
> +<<<<<<< HEAD
Он пока в разработке

2022-02-21 19:55 UTC, KenzheSan commented on src/components/BookCardRenderingDropdowns/BookStatusDropdown/BookStatusDropdown.js
> +=======
исправлю ,отправлю отдельным бранчем

2022-02-21 19:57 UTC, KenzheSan commented on src/components/BookCardRenderingDropdowns/BookStatusDropdown/BookStatusDropdown.js
> +=======
Done

2022-02-21 19:57 UTC, KenzheSan commented on src/components/BookCardRenderingDropdowns/BookStatusDropdown/BookStatusDropdown.js
> +>>>>>>> 00e1760282605c68c399d1f95006cfc25549a178
Done

2022-02-21 20:36 UTC, KenzheSan commented on src/components/UI/VendorBookCard/VendorBookCard.js
> +                  src={`http://3.123.114.41/static/download/${book.image.id}`}
done

2022-02-23 10:51 UTC, KenzheSan commented on src/containers/admin/adminAddBook/addAudioBook/AddAudioBook.js
> +               {/* <Input
желательно хотел отправить сначала бумажную книгу потом на аудио

2022-02-23 10:51 UTC, KenzheSan commented on src/containers/admin/adminAddBook/addAudioBook/AddAudioBook.js
> +               {/* <Input
если можно конечно

2022-02-23 11:12 UTC, zhumabek requested changes

2022-02-23 11:12 UTC, zhumabek commented on src/components/UI/dropZone/DropZone.js
> +   // const amazonImageUploadUrl = 'static/upload/image'
нужны нам эти комментарии?

2022-02-24 03:28 UTC, merged